#!/bin/sh

DAEMON="/usr/bin/aesdsocket"
PIDFILE="/var/run/aesdsocket.pid"

case "$1" in
    start)
        echo "Starting aesdsocket..."
        start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- -d
        echo "aesdsocket started with PID $(cat $PIDFILE)"
        ;;
        
    stop)
        echo "Stopping aesdsocket..."
        if [ -f $PIDFILE ]; then
            start-stop-daemon --stop --pidfile $PIDFILE --signal SIGTERM
            rm -f $PIDFILE
            echo "aesdsocket stopped."
        else
            echo "aesdsocket is not running."
        fi
        ;;
        
    restart)
        $0 stop
        sleep 2
        $0 start
        ;;
        
    status)
        if [ -f $PIDFILE ]; then
            echo "aesdsocket is running with PID $(cat $PIDFILE)"
        else
            echo "aesdsocket is not running."
        fi
        ;;
        
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
